pipeline {
    agent any

    environment {
        IMAGE_NAME = "cicd-next-app"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/your-username/cicd_app.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t $IMAGE_NAME ."
            }
        }

        stage('Stop Old Container') {
            steps {
                sh "docker rm -f cicd-app || true"
            }
        }

        stage('Run Container') {
            steps {
                sh "docker run -d -p 3000:3000 --name cicd-app $IMAGE_NAME"
            }
        }
    }
}